# Generated by Django 3.2.9 on 2021-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
