# Generated by Django 3.2.9 on 2021-11-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20211125_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
