# Generated by Django 3.2.9 on 2021-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
